- name: Verify project link of SonarCloud
  uri:
    url: 'https://sonarcloud.io/dashboard?id=helozano_cobol-calculator'
    headers:
      api_key: "ef20c9c6e19dcd60a9c89dddea8092ba1d48bc28"
      Accept: 'application/json'
    validate_certs: yes
    follow_redirects: all
    return_content: no
    status_code: 200
    method: GET
  register: get_nodes_out
  failed_when: "'FAILED' in get_nodes_out"
- debug: var=get_nodes_out
