- name: chek java packages is installed
  shell: dpkg-query --list | grep -i java | awk '{print $2,$3,$4,$5}'
  register: java_result

- debug:
      msg: "{{ java_result.stdout }}"
  when: java_result is success

- name: check java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_result

- debug:
      msg: "{{ java_result.stdout }}"

- name: "Check if GIT is installed"
  package_facts:
    manager: "auto"                                                                                                                                                                   
- name: "GIT test result"                                                                                                                                                     
  debug:                                                                                                                                                                        
    msg: "Git found"                                                                                                                                                          
  when: "'git' in ansible_facts.packages"                                                                                                                                                                                                                                                                                                               
- name: "Git test result"                                                                                                                                                     
  debug:                                                                                                                                                                        
    msg: "Git NOT found"                                                                                                                                                      
  when: "'git' not in ansible_facts.packages"

- stat:                                                                                                                                                                         
    path: /opt/apache-maven-3.6.3                                                                                                                                             
  register: result                                                                                                                                                          
- debug:                                                                                                                                                                        
    msg: "Maven is here"                                                                                                                                                      
  when: result.stat.exists                                                                                                                                                  
- debug:
    msg: "Maven is not installed"
  when: result.stat.exists==false
